<?php
/**
* One Pica
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to codemaster@onepica.com so we can send you a copy immediately.
*
* @category OnePica
* @package OnePica_ArqballSpin
* @copyright Copyright (c) 2012 One Pica, Inc. (http://www.onepica.com)
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
*/
/**
* One Pica Arqball Spin
*
* @category OnePica
* @package OnePica_ArqballSpin
* @author One Pica Codemaster codemaster@onepica.com
*/

$product	= Mage::registry('product');
$id			= $product->getId();
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Arqball Spins</h4>
    </div>
    <div class="fieldset fieldset-wide">
		<center>
			<input type="text" id="arqball_spin_search" value="" />
			<input type="button" id="arqball_spin_button" value="Search" />
			<div id="arqball_spin_content">
			</div>
			<script language="JavaScript">
				new ArqballSpin({
					containerId			: 'arqball_spin_content',
					searchFieldId		: 'arqball_spin_search',
					buttonId			: 'arqball_spin_button',
					requestUrl			: '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/grid/list/'.($id ? 'id/'.$id.'/' : '')) ?>'
				})
			</script>
		</center>
	</div>
</div>